# Generated by Django 4.2.13 on 2024-11-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DesignSystemAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=250, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=250, verbose_name="Last name"),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Birth date"),
                ),
            ],
            options={
                "verbose_name": "design_system DesignSystemAuthor",
            },
        ),
        migrations.CreateModel(
            name="DesignSystemGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=15, verbose_name="Code")),
                (
                    "designation",
                    models.CharField(max_length=250, verbose_name="Designation"),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Help text"
                    ),
                ),
            ],
            options={
                "verbose_name": "design_system DesignSystemGenre",
            },
        ),
        migrations.CreateModel(
            name="DesignSystemBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Title")),
                (
                    "number_of_pages",
                    models.CharField(
                        blank=True, max_length=6, verbose_name="Number of pages"
                    ),
                ),
                (
                    "book_format",
                    models.CharField(
                        blank=True,
                        choices=[("PAPER", "Paper"), ("NUM", "Digital")],
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="example_design_system.designsystemauthor",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        to="example_design_system.designsystemgenre"
                    ),
                ),
            ],
            options={
                "verbose_name": "design_system DesignSystemBook",
            },
        ),
    ]
